allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  '@ffprobe-installer/darwin-arm64': true
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  vue-demi: true

minimumReleaseAge: 0
