/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicSettings: typeof import('./src/components/basic-settings.vue')['default']
    CeilButtons: typeof import('./src/components/ceil-buttons.vue')['default']
    CopyrightInfo: typeof import('./src/components/copyright-info.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FloorButtons: typeof import('./src/components/floor-buttons.vue')['default']
    NavigationBar: typeof import('./src/components/navigation-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./src/components/settings-card.vue')['default']
    SettingsContent: typeof import('./src/components/settings-content.vue')['default']
    VideoItem: typeof import('./src/components/video-item.vue')['default']
    VideoList: typeof import('./src/components/video-list.vue')['default']
  }
}
